[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "comp_chem_agent"
version = "0.1.0"
description = "A computational chemistry agent for molecular simulation tasks."
authors = [
    { name = "Thang Pham", email = "tpham@anl.gov" }
]
requires-python = ">=3.10"
dependencies = [
    "pydantic>=1.8.2",
    "ase>=3.22.0",
    "rdkit>=2024.03.5",
    "langgraph>=0.2.59",
    "langchain-openai>=0.2.12",
    "langchain-ollama>=0.2.1",
    "pydantic>=2.10.3",
    "pandas>=2.2"]

[project.urls]
"Homepage" = "https://example.com/your-project"
"Repository" = "https://github.com/Autonomous-Scientific-Agents/CompChemAgent/tree/main"

[tool.setuptools.packages.find]
where = ["src/"]
