[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "comp_chem_agent"
version = "0.1.0"
description = "A computational chemistry agent package for HPC job management."
authors = [
    { name = "Thang Pham", email = "your.email@example.com" }
]
requires-python = ">=3.8"
dependencies = [
    "pydantic>=1.8.2",
    "ase>=3.22.0",
    "rdkit>=2024.03.5"]

[project.urls]
"Homepage" = "https://example.com/your-project"
"Repository" = "https://github.com/your-username/comp_chem_agent"

[tool.setuptools.packages.find]
where = ["src/"]
